clean up mlops/mlcomp/deputy makefile
mlpiper/mlpiper pull request #145
Opened 2019-06-14 22:26 UTC by yakov-g

- move egg to the top, so it is default target taken by 'make' command
- create symlinks together with eggs, so it would be more convenient to
run manually - just `make`

2019-06-16 09:48 UTC, zohar-mizrahi requested changes

2019-06-16 09:48 UTC, zohar-mizrahi commented on mlops/Makefile
> +# Put it first so that "make" without argument is like "make help". Doesn't work now.
Is this comment still relevant?

2019-06-17 16:15 UTC, zohar-mizrahi approved these changes

2019-06-18 02:38 UTC, liororama approved these changes

2019-06-18 04:00 UTC, merged